language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y -qq debhelper libmysqlclient-dev quilt
                             autotools-dev dh-autoreconf fakeroot
                             rsync

before_script:
    - mkdir libnss-mysql-bg-1.5
    - rsync -Paz --exclude-from 'rsync-exclude.txt' * libnss-mysql-bg-1.5/
    - cd libnss-mysql-bg-1.5

script:
    - debian/rules clean
    - debian/rules build
    - fakeroot debian/rules binary
